// Regenerates lib/src/board_matcher_library.dart by embedding upstream
// @sabaki/boardmatcher's library.json verbatim.
//
// Usage:
//   dart run tool/regen_board_matcher_library.dart [path/to/library.json]
//
// The default path assumes a sibling boardmatcher checkout:
//   ../boardmatcher/library/library.json
//
// To upgrade the embedded library:
//   1. Pull a fresh copy of @sabaki/boardmatcher.
//   2. Run this script.
//   3. Run `dart test test/board_matcher_test.dart` to confirm the
//      published count and Sabaki fixtures still pass.

import 'dart:io';

const _defaultSource = '../boardmatcher/library/library.json';
const _outputPath = 'lib/src/board_matcher_library.dart';

void main(List<String> args) {
  final source = args.isNotEmpty ? args.first : _defaultSource;
  final input = File(source);
  if (!input.existsSync()) {
    stderr.writeln('library.json not found: $source');
    stderr.writeln('Pass an explicit path: '
        'dart run tool/regen_board_matcher_library.dart <path>');
    exitCode = 2;
    return;
  }

  final raw = input.readAsStringSync();
  if (raw.contains("'''")) {
    stderr.writeln(
        'Embedded JSON contains triple single-quotes; raw-string '
        'embedding would break. Aborting.');
    exitCode = 3;
    return;
  }

  final out = StringBuffer()
    ..writeln('// Embedded copy of @sabaki/boardmatcher\'s library/library.json.')
    ..writeln('// Generated by tool/regen_board_matcher_library.dart from')
    ..writeln('// $source — do not edit by hand.')
    ..writeln()
    ..writeln('/// Raw JSON of Sabaki\'s curated 58-pattern opening library. Parsed')
    ..writeln('/// lazily by [BoardMatcher.defaultLibrary].')
    ..write("const String defaultLibraryJson = r'''")
    ..write(raw)
    ..writeln("''';");

  File(_outputPath).writeAsStringSync(out.toString());
  stdout.writeln('Wrote ${raw.length} bytes of JSON → $_outputPath');
}
